plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - message: 'chore(release): ${nextRelease.version} [skip release]'

repositoryUrl: https://github.com/dhose/go-turfgame-exporter.git

branches:
  - main
